server:
  port: 8080

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
#      cluster-nodes: 139.196.86.51:9300
      cluster-name: elasticsearch

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.8.66:3306/think_tank?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: yuwubao
    password: 12345
    tomcat:
      max-active: 20
      max-idle: 10
      min-idle: 5
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  http:
    multipart:
      max-file-size: 100Mb
  aop:
    auto: true
#    proxy-target-class: false
logging:
  level: warn
  file: hb_zkw-v1.log
security:
  basic:
    authorize-mode: none